import Head from 'next/head'
import { Heading, Container, Stack, Text, Button, Image, Input, FormControl, FormLabel, FormHelperText } from '@chakra-ui/react'
import { Box } from '@chakra-ui/react'

const Home = () => {
  return (
    <Container maxW={'5xl'}>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.js" type="text/javascript" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.dom.min.js" type="text/javascript"  ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.sound.min.js" type="text/javascript" ></script>
      <script src="https://unpkg.com/ml5@latest/dist/ml5.min.js" type="text/javascript" ></script>
      <script src="/script/sketch.js" type="text/javascript" ></script>
      <script src="/script/songle.js" type="text/javascript" ></script>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />

      <Stack
        textAlign={'center'}
        align={'center'}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 20, md: 28 }}>

        <Heading
          fontWeight={600}
          fontSize={{ base: '3xl', sm: '4xl', md: '6xl' }}
          lineHeight={'100%'}>
          あなたに最適な {' '} <br />
          <Text as={'span'} color={'orange.400'}>
            カラオケキーを見つける
          </Text>
        </Heading>

        <Text color={'gray.600'} maxW={'4xl'} fontSize='xl'>
          気持ちよく歌えるカラオケのキーが見つからなくて困っていませんか。 <br />
          このサイトなら、たった３ステップで気持ちのよいキーをみつけることができます。<br /> <br />

          ※キーを見つけるには、歌う必要があります。騒音トラブル等には十分気をつけてください。
        </Text>

        <Image src="/Karaoke-bro.png"></Image>
      </Stack>
      <br />

      <Stack p="4" boxShadow="lg" m="4" borderRadius="sm">
        <Heading as='h3' size='lg'>
          step1.音楽の選択
        </Heading>

        <Text color={'gray.600'} maxW={'4xl'}>
          Youtubeのリンクを貼り付けてください．
        </Text>

        <FormControl>
          <FormLabel htmlFor='email'>Youtube リンク</FormLabel>
          <Input id='email' type='email' />
        </FormControl>

        <Button onClick={() => run(recorder1)}>読み取り</Button>

      </Stack>

      <Stack p="4" boxShadow="lg" m="4" borderRadius="sm">
        <Heading as='h3' size='lg'>
          step1.音楽を効く
        </Heading>

        <Text color={'gray.600'} maxW={'4xl'}>
          まず、対象の曲を聞いてください。クリックすると曲のサビが流れます。
        </Text>

        <div id="songle-yt"></div>
        <div id="songle-sw"></div>
      </Stack>


      <Stack p="4" boxShadow="lg" m="4" borderRadius="sm">
        <Heading as='h3' size='lg'>
          step2.原曲キーで歌う
        </Heading>

        <Text color={'gray.600'} maxW={'4xl'}>
          下のボタンを押して曲のサビを原曲キーで歌ってください．
        </Text>

        <Button onClick={() => run(recorder1)}>One</Button>
        {/* <p id='status'>ローディング中</p> */}
        {/* <p id='result'>No pitch detected</p> */}

      </Stack>

      <Stack p="4" boxShadow="lg" m="4" borderRadius="sm">
        <Heading as='h3' size='lg'>
          step3.好きなキーで歌う
        </Heading>

        <Text color={'gray.600'} maxW={'4xl'}>
          下のボタンを押して曲のサビを好きなキーで歌ってください．
        </Text>

        <Button onClick={() => run(recorder2)}>Second</Button>
        {/* <Button onClick={() => alert(calcAvarageDiff())}>Result</Button> */}
      </Stack>

      <a href="https://storyset.com/people">People illustrations by Storyset</a>
    </Container>

  )
}

export default Home
